// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// haplo_2_geno
Eigen::MatrixXd haplo_2_geno(const Eigen::MatrixXd haplo, bool snps_in_rows);
RcppExport SEXP _SeqSupport_haplo_2_geno(SEXP haploSEXP, SEXP snps_in_rowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type haplo(haploSEXP);
    Rcpp::traits::input_parameter< bool >::type snps_in_rows(snps_in_rowsSEXP);
    rcpp_result_gen = Rcpp::wrap(haplo_2_geno(haplo, snps_in_rows));
    return rcpp_result_gen;
END_RCPP
}
// haplo_2_geno_i
Eigen::MatrixXi haplo_2_geno_i(const Eigen::MatrixXi haplo, bool snps_in_rows);
RcppExport SEXP _SeqSupport_haplo_2_geno_i(SEXP haploSEXP, SEXP snps_in_rowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXi >::type haplo(haploSEXP);
    Rcpp::traits::input_parameter< bool >::type snps_in_rows(snps_in_rowsSEXP);
    rcpp_result_gen = Rcpp::wrap(haplo_2_geno_i(haplo, snps_in_rows));
    return rcpp_result_gen;
END_RCPP
}
// match_sorted_exp
Rcpp::IntegerVector match_sorted_exp(const Rcpp::IntegerVector& query, const Rcpp::IntegerVector& target);
RcppExport SEXP _SeqSupport_match_sorted_exp(SEXP querySEXP, SEXP targetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type query(querySEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type target(targetSEXP);
    rcpp_result_gen = Rcpp::wrap(match_sorted_exp(query, target));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SeqSupport_haplo_2_geno", (DL_FUNC) &_SeqSupport_haplo_2_geno, 2},
    {"_SeqSupport_haplo_2_geno_i", (DL_FUNC) &_SeqSupport_haplo_2_geno_i, 2},
    {"_SeqSupport_match_sorted_exp", (DL_FUNC) &_SeqSupport_match_sorted_exp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_SeqSupport(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
