# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

haplo_2_geno <- function(haplo, snps_in_rows = TRUE) {
    .Call('_SeqSupport_haplo_2_geno', PACKAGE = 'SeqSupport', haplo, snps_in_rows)
}

haplo_2_geno_i <- function(haplo, snps_in_rows = TRUE) {
    .Call('_SeqSupport_haplo_2_geno_i', PACKAGE = 'SeqSupport', haplo, snps_in_rows)
}

match_sorted <- function(query, target) {
    .Call('_SeqSupport_match_sorted_exp', PACKAGE = 'SeqSupport', query, target)
}

map_eQTL_h5 <- function(SNP_path, EXP_path, out_path, SNP_chunksize = 20000L, EXP_chunksize = -1L) {
    invisible(.Call('_SeqSupport_map_eQTL_h5', PACKAGE = 'SeqSupport', SNP_path, EXP_path, out_path, SNP_chunksize, EXP_chunksize))
}

crossprod_h5 <- function(filenames, groupnames, datanames) {
    invisible(.Call('_SeqSupport_crossprod_h5', PACKAGE = 'SeqSupport', filenames, groupnames, datanames))
}

crossprod_quh_h5 <- function(q_dff, uh_dff, quh_dff) {
    invisible(.Call('_SeqSupport_crossprod_quh_h5', PACKAGE = 'SeqSupport', q_dff, uh_dff, quh_dff))
}

map_eQTL_chunk_h5 <- function(snp_dff, exp_dff, uhat_dff, se_dff) {
    invisible(.Call('_SeqSupport_map_eQTL_chunk_h5', PACKAGE = 'SeqSupport', snp_dff, exp_dff, uhat_dff, se_dff))
}

read_ld_chunk_h5 <- function(filename, ld_chunk) {
    .Call('_SeqSupport_read_ld_chunk_h5', PACKAGE = 'SeqSupport', filename, ld_chunk)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_SeqSupport_RcppExport_registerCCallable', PACKAGE = 'SeqSupport')
})
