# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cont_reg <- function(input_rows = as.integer( c()), input_cols = as.integer( c()), chunksizes = as.integer( c(0,0)), dimsize = as.integer( c(0,0)), chunk_group = 0L) {
    .Call('_SeqSupport_cont_reg', PACKAGE = 'SeqSupport', input_rows, input_cols, chunksizes, dimsize, chunk_group)
}

map_eQTL_h5 <- function(SNP_path, EXP_path, out_path, SNP_chunksize = 20000L, EXP_chunksize = -1L) {
    invisible(.Call('_SeqSupport_map_eQTL_h5', PACKAGE = 'SeqSupport', SNP_path, EXP_path, out_path, SNP_chunksize, EXP_chunksize))
}

crossprod_h5 <- function(filenames, groupnames, datanames) {
    invisible(.Call('_SeqSupport_crossprod_h5', PACKAGE = 'SeqSupport', filenames, groupnames, datanames))
}

crossprod_quh_h5 <- function(q_dff, uh_dff, quh_dff) {
    invisible(.Call('_SeqSupport_crossprod_quh_h5', PACKAGE = 'SeqSupport', q_dff, uh_dff, quh_dff))
}

sim_U <- function(n, tsigu) {
    .Call('_SeqSupport_sim_U_exp', PACKAGE = 'SeqSupport', n, tsigu)
}

simulate_y_h5 <- function(in_dff, out_dff, p, N, g, tsigu) {
    .Call('_SeqSupport_simulate_y_h5', PACKAGE = 'SeqSupport', in_dff, out_dff, p, N, g, tsigu)
}

map_eQTL_chunk_h5 <- function(snp_dff, exp_dff, uhat_dff, se_dff) {
    invisible(.Call('_SeqSupport_map_eQTL_chunk_h5', PACKAGE = 'SeqSupport', snp_dff, exp_dff, uhat_dff, se_dff))
}

read_ld_chunk_h5 <- function(filename, ld_chunk) {
    .Call('_SeqSupport_read_ld_chunk_h5', PACKAGE = 'SeqSupport', filename, ld_chunk)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_SeqSupport_RcppExport_registerCCallable', PACKAGE = 'SeqSupport')
})
