# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ld_p_h5 <- function(input_filename, output_filename, subset_snp, snp_id, subset_ind, map, chunksize = 10000L) {
    invisible(.Call(`_SeqSupport_ld_p_h5`, input_filename, output_filename, subset_snp, snp_id, subset_ind, map, chunksize))
}

center_columns <- function(mat) {
    .Call(`_SeqSupport_center_columns_exp`, mat)
}

calc_uh_se_exp <- function(input_snpmat, input_expmat, parallel = FALSE) {
    .Call(`_SeqSupport_calc_uh_se_exp`, input_snpmat, input_expmat, parallel)
}

evd_rnorm_i <- function(Q, s, vm) {
    .Call(`_SeqSupport_evd_rnorm_i`, Q, s, vm)
}

crossprod_quh_h5 <- function(file_l, doTranspose = TRUE, allele_flip = as.numeric( c())) {
    invisible(.Call(`_SeqSupport_crossprod_quh_h5`, file_l, doTranspose, allele_flip))
}

sim_U <- function(n, tsigu, chunksize = 2L) {
    .Call(`_SeqSupport_sim_U_exp`, n, tsigu, chunksize)
}

calc_af_h5 <- function(file_l, options) {
    .Call(`_SeqSupport_calc_af_h5`, file_l, options)
}

est_spve_h5 <- function(file_l, N, sigu, rel_D_cutoff = 0.01) {
    .Call(`_SeqSupport_est_spve_h5`, file_l, N, sigu, rel_D_cutoff)
}

orthogonalize_data <- function(data, ortho_covar) {
    .Call(`_SeqSupport_orthogonalize_data`, data, ortho_covar)
}

orthogonalize_covars <- function(Covariates) {
    .Call(`_SeqSupport_orthogonalize_covars`, Covariates)
}

map_eQTL_chunk_h5 <- function(snp_dff, exp_dff, uhat_dff, se_dff, Covariates, options) {
    invisible(.Call(`_SeqSupport_map_eQTL_chunk_h5`, snp_dff, exp_dff, uhat_dff, se_dff, Covariates, options))
}

